modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="alchemaigica"
version="0.0.1"
displayName="AlcheMaigica"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Xponer2, Resseter"

[[dependencies.alchemaigica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.alchemaigica]]
    modId="geckolib"
    mandatory=false
    ordering="NONE"
    side="BOTH"

