modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="quarrycraft"
version="0.0.1"
displayName="quarryCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Xponer2, Resseter"

[[dependencies.quarrycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




