modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="quarrycraft"
version="1.0.0"
displayName="quarryCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Þðà, MCreator"

[[dependencies.quarrycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.quarrycraft]]
    modId="geckolib"
    mandatory=false
    ordering="NONE"
    side="BOTH"

